apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapier-deployment

  labels:
    app: zapier-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zapier-deployment
  template:
    metadata:
      labels:
        app: zapier-deployment
    spec:
      containers:
      - name: zapier-deployment
        image: myimage:latest
        ports:
        - containerPort: 3000
