apiVersion: v1
kind: Service
metadata:
  name: basic-deployment-Service
  namespace: zapier-basic
spec:
  type: NodePort
  selector:
    app: zapier-deployment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
