apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/service.yaml
  - rollout-staging.yaml

namePrefix: staging-
nameSuffix: ""

patches:
  - path: replicas-patch.yaml
    target:
      kind: Rollout
      name: zapier-deployment
