apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout-bluegreen.yaml
  - service-rollout-active.yaml
  - service-rollout-preview.yaml

namePrefix: staging-
nameSuffix: ""

patches:
  - path: replicas-patch.yaml
    target:
      kind: Rollout
      name: zapier-deployment
