apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: zapier-deployment
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: staging-zapier-service
      previewService: staging-zapier-preview-service
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: zapier-deployment
  template:
    metadata:
      labels:
        app: zapier-deployment
    spec:
      containers:
        - name: zapier-deployment
          image: siddhantmunjamkar/zapier-clone:v2
          ports:
            - containerPort: 80 
