apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-application-zapier
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SiddhantMunjamkar/GitOpsNavigator.git
    targetRevision: HEAD
    path: manifests/gitops/basic
  destination:
    server: https://kubernetes.default.svc
    namespace: zapier-basic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
