apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

namePrefix: dev-
nameSuffix: ""

patchesS:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: application-zapier-dev
