apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapier-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: zapier-deployment
        - image: siddhantmunjamkar/zapier-clone:latest
          ports:
            - containerPort: 3000
