apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapier-deployment
  namespace: zapier-dev  
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: zapier-deployment
          image: siddhantmunjamkar/zapier-clone:latest
