apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: zapier-deployment
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: zapier-service
      previewService: zapier-preview-service
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: zapier-deployment
  template:
    metadata:
      labels:
        app: zapier-deployment
    spec:
      containers:
        - name: zapier-container
          image: siddhantmunjamkar/zapier-clone:latest
          ports:
            - containerPort: 3000
