apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zapier-staging

resources:
  - ../../base/service.yaml
  - rollout-canary.yaml

namePrefix: prod-
nameSuffix: ""

patchesStrategicMerge:
  - replicas-patch.yaml
