apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: zapier-rollout-prod
spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10}
        - setWeight: 40
        - pause: { duration: 20 }
        - setWeight: 60
        - pause: { duration: 30 }
        - setWeight: 80
        - pause: { duration: 40 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app:  zapier-rollout-prod
  template:
    metadata:
      labels:
        app:  zapier-rollout-prod
    spec:
      containers:
        - name:  zapier-rollout-prod
          image: siddhantmunjamkar/zapier-clone:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
