apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  metrics:
    - name: error-rate
      interval: 30s
      failureLimit: 3
      successCondition: result < 0.05
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc.cluster.local:9090
          query: |
            1 - (
              sum(rate(http_requests_total{status=~"5.."}[1m])) /
              sum(rate(http_requests_total[1m]))
            )
