apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout-canary.yaml
  - service-rollout-canary.yaml

namePrefix: prod-
nameSuffix: ""

patches:
  - path: replicas-patch.yaml
    target:
      kind: Rollout
      name: zapier-deployment
