apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: zapier-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8090"

spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 10 }
        - setWeight: 40
        - pause: { duration: 20 }
        - setWeight: 60
        - pause: { duration: 30 }
        - setWeight: 80
        - pause: { duration: 40 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zapier-deployment
  template:
    metadata:
      labels:
        app: zapier-deployment
      annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3000" # ← Use the port your app listens on
      prometheus.io/path: "/metrics" # ← Optional if using a custom path
    spec:
      containers:
        - name: zapier-deployment
          image: siddhantmunjamkar/zapier-clone:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
