apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-rollouts-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  namespaceSelector:
    matchNames:
      - argo-rollouts
  endpoints:
    - port: metrics
      interval: 15s
